### ISSUE TITLE
Explicit source for data files

### ISSUE THREAD

**Issue by mwilliamson-healx** [libChEBI/libChEBIpy#7]
For reproducibility, it would be useful for us to be able to specify the source data files, rather than having them automatically update. I'm happy to put together a pull request, but wanted to check whether this was something you'd already thought about at all?

**Comment by neilswainston** [comment]
Hi Michael,

Sorry for the delay. No, I hadn’t considered this.

Thanks for the update. I’ve not checked, but I’m assuming that the default behaviour is still auto-downloading and updating?

Cheers,

Neil.

Neil Swainston, PhD
Senior Experimental Officer

Centre for Synthetic Biology of Fine and Speciaity Chemicals (SYNBIOCHEM)
Manchester Institute of Biotechnology
University of Manchester
Manchester M1 7DN
United Kingdom

On 3 Oct 2016, at 15:01, Michael Williamson <notifications@github.com<mailto:notifications@github.com>> wrote:


For reproducibility, it would be useful for us to be able to specify the source data files, rather than having them automatically update. I'm happy to put together a pull request, but wanted to check whether this was something you'd already thought about at all?

**Comment by mwilliamson-healx** [comment]
No worries about the delay! Yes, the default behaviour is unchanged.

**Comment by mwilliamson-healx** [comment]
This was implemented in #8, so closing this issue.
